{
 "title": "1.公有云-告警看板",
 "description": "从数据库中查询告警数据",
 "tags": [
  "alertmanager",
  "prometheus"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ENV", "label": "环境", "query": "com,cn,me,priv,ops" }
  ]
 },
 "panels": [
  { "title": "实时告警", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "告警总数",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(fingerprint)\nFROM alertmanager\nWHERE\n  JSON_EXTRACT(statusss, \"$.silencedBy[0]\") is null \n  and JSON_EXTRACT(statusss, \"$.state\") = \"active\"\n  and env = '$ENV'\nORDER BY startsAt"
    }
   ]
  },
  {
   "title": "数据库告警",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  count(fingerprint) as \"慢查询\"\r\nFROM alertmanager\r\nWHERE\r\n  JSON_EXTRACT(statusss, \"$.silencedBy[0]\") is null \r\n  and JSON_EXTRACT(statusss, \"$.state\") = \"active\"\r\n  and env='$ENV'  \r\n  and category = \"数据库慢查询\"\r\nORDER BY startsAt"
    },
    {
     "rawSql": "SELECT\n  count(fingerprint) as \"连接数高\"\nFROM alertmanager\nWHERE\n  JSON_EXTRACT(statusss, \"$.silencedBy[0]\") is null \n  and JSON_EXTRACT(statusss, \"$.state\") = \"active\"\n  and env='$ENV'  \n  and category = \"数据库连接数高\"\nORDER BY startsAt"
    },
    {
     "rawSql": "SELECT\r\n  count(fingerprint) as \"行锁\"\r\nFROM alertmanager\r\nWHERE\r\n  JSON_EXTRACT(statusss, \"$.silencedBy[0]\") is null \r\n  and JSON_EXTRACT(statusss, \"$.state\") = \"active\"\r\n  and env='$ENV'  \r\n  and category = \"数据库行锁\"\r\nORDER BY startsAt"
    },
    {
     "rawSql": "SELECT\r\n  count(fingerprint) as \"内存高\"\r\nFROM alertmanager\r\nWHERE\r\n  JSON_EXTRACT(statusss, \"$.silencedBy[0]\") is null \r\n  and JSON_EXTRACT(statusss, \"$.state\") = \"active\"\r\n  and env='$ENV'  \r\n  and category = \"数据库内存高\"\r\nORDER BY startsAt"
    },
    {
     "rawSql": "SELECT\r\n  count(fingerprint) as \"CPU高\"\r\nFROM alertmanager\r\nWHERE\r\n  JSON_EXTRACT(statusss, \"$.silencedBy[0]\") is null \r\n  and JSON_EXTRACT(statusss, \"$.state\") = \"active\"\r\n  and env='$ENV'  \r\n  and category = \"数据库CPU高\"\r\nORDER BY startsAt"
    },
    {
     "rawSql": "SELECT\r\n  count(fingerprint) as \"磁盘高\"\r\nFROM alertmanager\r\nWHERE\r\n  JSON_EXTRACT(statusss, \"$.silencedBy[0]\") is null \r\n  and JSON_EXTRACT(statusss, \"$.state\") = \"active\"\r\n  and env='$ENV'  \r\n  and category = \"数据库磁盘高\"\r\nORDER BY startsAt"
    },
    {
     "rawSql": "SELECT\r\n  count(fingerprint) as \"从库\"\r\nFROM alertmanager\r\nWHERE\r\n  JSON_EXTRACT(statusss, \"$.silencedBy[0]\") is null \r\n  and JSON_EXTRACT(statusss, \"$.state\") = \"active\"\r\n  and env='$ENV'  \r\n  and category = \"数据库从库\"\r\nORDER BY startsAt"
    },
    {
     "rawSql": "SELECT\r\n  count(fingerprint) as \"宕机\"\r\nFROM alertmanager\r\nWHERE\r\n  JSON_EXTRACT(statusss, \"$.silencedBy[0]\") is null \r\n  and JSON_EXTRACT(statusss, \"$.state\") = \"active\"\r\n  and env='$ENV'  \r\n  and category = \"数据库宕机\"\r\nORDER BY startsAt"
    }
   ]
  },
  {
   "title": "Redis告警",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(fingerprint) as \"超流控\"\nFROM alertmanager\nWHERE\n  JSON_EXTRACT(statusss, \"$.silencedBy[0]\") is null \n  and JSON_EXTRACT(statusss, \"$.state\") = \"active\"\n  and env='$ENV'  \n  and category = \"Redis超流控\"\nORDER BY startsAt"
    },
    {
     "rawSql": "SELECT\n  count(fingerprint) \"带宽高\"\nFROM alertmanager\nWHERE\n  JSON_EXTRACT(statusss, \"$.silencedBy[0]\") is null \n  and JSON_EXTRACT(statusss, \"$.state\") = \"active\"\n  and env='$ENV'  \n  and category = \"Redis带宽高\"\nORDER BY startsAt"
    },
    {
     "rawSql": "SELECT\r\n  count(fingerprint) as \"CPU高\"\r\nFROM alertmanager\r\nWHERE\r\n  JSON_EXTRACT(statusss, \"$.silencedBy[0]\") is null \r\n  and JSON_EXTRACT(statusss, \"$.state\") = \"active\"\r\n  and env='$ENV'  \r\n  and category = \"RedisCPU高\"\r\nORDER BY startsAt"
    },
    {
     "rawSql": "SELECT\r\n  count(fingerprint) as \"内存高\"\r\nFROM alertmanager\r\nWHERE\r\n  JSON_EXTRACT(statusss, \"$.silencedBy[0]\") is null \r\n  and JSON_EXTRACT(statusss, \"$.state\") = \"active\"\r\n  and env='$ENV'  \r\n  and category = \"Redis内存高\"\r\nORDER BY startsAt"
    }
   ]
  },
  {
   "title": "Nginx告警",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(fingerprint) as \"慢\"\nFROM alertmanager\nWHERE\n  JSON_EXTRACT(statusss, \"$.silencedBy[0]\") is null \n  and JSON_EXTRACT(statusss, \"$.state\") = \"active\"\n  and env='$ENV'  \n  and category = \"nginx慢\"\nORDER BY startsAt"
    },
    {
     "rawSql": "SELECT\n  count(fingerprint) as \"【5XX】\"\nFROM alertmanager\nWHERE\n  JSON_EXTRACT(statusss, \"$.silencedBy[0]\") is null \n  and JSON_EXTRACT(statusss, \"$.state\") = \"active\"\n  and env='$ENV'  \n  and category = \"nginx5xx\"\nORDER BY startsAt"
    },
    {
     "rawSql": "SELECT\n  count(fingerprint) as \"【4XX】\"\nFROM alertmanager\nWHERE\n  JSON_EXTRACT(statusss, \"$.silencedBy[0]\") is null \n  and JSON_EXTRACT(statusss, \"$.state\") = \"active\"\n  and env='$ENV'  \n  and category = \"nginx4xx\"\nORDER BY startsAt"
    }
   ]
  },
  {
   "title": "JVM告警",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  count(fingerprint) as \"内存高\"\r\nFROM alertmanager\r\nWHERE\r\n  JSON_EXTRACT(statusss, \"$.state\") = \"active\"\r\n  and env='$ENV'  \r\n  and category = \"java内存高\"\r\nORDER BY startsAt"
    },
    {
     "rawSql": "SELECT\r\n  count(fingerprint) as \"FGC\"\r\nFROM alertmanager\r\nWHERE\r\n  JSON_EXTRACT(statusss, \"$.state\") = \"active\"\r\n  and env='$ENV'  \r\n  and category = \"javaFGC\"\r\nORDER BY startsAt"
    },
    {
     "rawSql": "SELECT\n  count(fingerprint) as \"连接高/等待\"\nFROM alertmanager\nWHERE\n  JSON_EXTRACT(statusss, \"$.state\") = \"active\"\n  and env='$ENV'  \n  and category = \"java连接高/等待\"\nORDER BY startsAt"
    },
    {
     "rawSql": "SELECT\n  count(fingerprint) as \"服务宕机\"\nFROM alertmanager\nWHERE\n  JSON_EXTRACT(statusss, \"$.state\") = \"active\"\n  and env='$ENV'  \n  and category = \"java服务宕机\"\nORDER BY startsAt"
    }
   ]
  },
  {
   "title": "应用告警",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  count(fingerprint) as \"CPU高\"\r\nFROM alertmanager\r\nWHERE\r\n  JSON_EXTRACT(statusss, \"$.silencedBy[0]\") is null \r\n  and JSON_EXTRACT(statusss, \"$.state\") = \"active\"\r\n  and env='$ENV'  \r\n  and category = \"应用CPU高\"\r\nORDER BY startsAt"
    },
    {
     "rawSql": "SELECT\r\n  count(fingerprint) as \"内存高\"\r\nFROM alertmanager\r\nWHERE\r\n  JSON_EXTRACT(statusss, \"$.silencedBy[0]\") is null \r\n  and JSON_EXTRACT(statusss, \"$.state\") = \"active\"\r\n  and env='$ENV'  \r\n  and category = \"应用内存高\"\r\nORDER BY startsAt"
    },
    {
     "rawSql": "SELECT\n  count(fingerprint) as \"线程忙\"\nFROM alertmanager\nWHERE\n  JSON_EXTRACT(statusss, \"$.silencedBy[0]\") is null \n  and JSON_EXTRACT(statusss, \"$.state\") = \"active\"\n  and env='$ENV'  \n  and category = \"应用线程忙\"\nORDER BY startsAt"
    }
   ]
  },
  {
   "title": "RabbitMQ 告警",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  count(fingerprint) as \"非delay队列\"\r\nFROM alertmanager\r\nWHERE\r\n  JSON_EXTRACT(statusss, \"$.silencedBy[0]\") is null \r\n  and JSON_EXTRACT(statusss, \"$.state\") = \"active\"\r\n  and env='$ENV'  \r\n  and category = \"MQ非delay队列\"\r\nORDER BY startsAt"
    },
    {
     "rawSql": "SELECT\r\n  count(fingerprint) as \"delay队列\"\r\nFROM alertmanager\r\nWHERE\r\n  JSON_EXTRACT(statusss, \"$.silencedBy[0]\") is null \r\n  and JSON_EXTRACT(statusss, \"$.state\") = \"active\"\r\n  and env='$ENV'  \r\n  and category = \"MQdelay队列\"\r\nORDER BY startsAt"
    },
    {
     "rawSql": "SELECT\r\n  count(fingerprint) as \"MQ宕机\"\r\nFROM alertmanager\r\nWHERE\r\n  JSON_EXTRACT(statusss, \"$.silencedBy[0]\") is null \r\n  and JSON_EXTRACT(statusss, \"$.state\") = \"active\"\r\n  and env='$ENV'  \r\n  and category = \"MQ宕机\"\r\n  ORDER BY startsAt"
    },
    {
     "rawSql": "SELECT\r\n  count(fingerprint) as \"内存高\"\r\nFROM alertmanager\r\nWHERE\r\n  JSON_EXTRACT(statusss, \"$.silencedBy[0]\") is null \r\n  and JSON_EXTRACT(statusss, \"$.state\") = \"active\"\r\n  and env='$ENV'  \r\n  and category = \"MQ内存高\"\r\nORDER BY startsAt"
    },
    {
     "rawSql": "SELECT\r\n  count(fingerprint) as \"连接数高\"\r\nFROM alertmanager\r\nWHERE\r\n  JSON_EXTRACT(statusss, \"$.silencedBy[0]\") is null \r\n  and JSON_EXTRACT(statusss, \"$.state\") = \"active\"\r\n  and env='$ENV'  \r\n  and category = \"MQ连接数高\"\r\nORDER BY startsAt"
    },
    {
     "rawSql": "SELECT\r\n  count(fingerprint) as \"磁盘\"\r\nFROM alertmanager\r\nWHERE\r\n  JSON_EXTRACT(statusss, \"$.silencedBy[0]\") is null \r\n  and JSON_EXTRACT(statusss, \"$.state\") = \"active\"\r\n  and env='$ENV'  \r\n  and category = \"MQ磁盘高\"\r\nORDER BY startsAt"
    }
   ]
  },
  {
   "title": "探针告警",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  count(fingerprint) as \"URL慢\"\r\nFROM alertmanager\r\nWHERE\r\n  JSON_EXTRACT(statusss, \"$.silencedBy[0]\") is null \r\n  and JSON_EXTRACT(statusss, \"$.state\") = \"active\"\r\n  and env='$ENV'  \r\n  and category = \"URL慢\"\r\nORDER BY startsAt"
    },
    {
     "rawSql": "SELECT\r\n  count(fingerprint) as \"URL故障\"\r\nFROM alertmanager\r\nWHERE\r\n  JSON_EXTRACT(statusss, \"$.silencedBy[0]\") is null \r\n  and JSON_EXTRACT(statusss, \"$.state\") = \"active\"\r\n  and env='$ENV'  \r\n  and category = \"URL故障\"\r\nORDER BY startsAt"
    },
    {
     "rawSql": "SELECT\r\n  count(fingerprint) as \"SSL证书\"\r\nFROM alertmanager\r\nWHERE\r\n  JSON_EXTRACT(statusss, \"$.silencedBy[0]\") is null \r\n  and JSON_EXTRACT(statusss, \"$.state\") = \"active\"\r\n  and env='$ENV'  \r\n  and category = \"URLSSL证书\"\r\nORDER BY startsAt"
    }
   ]
  },
  {
   "title": "Zookeeper告警",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  count(fingerprint) as \"宕机\"\r\nFROM alertmanager\r\nWHERE\r\n  JSON_EXTRACT(statusss, \"$.silencedBy[0]\") is null \r\n  and JSON_EXTRACT(statusss, \"$.state\") = \"active\"\r\n  and env='$ENV'  \r\n  and category = \"ZK宕机\"\r\nORDER BY startsAt"
    },
    {
     "rawSql": "SELECT\r\n  count(fingerprint) as \"Leader异常\"\r\nFROM alertmanager\r\nWHERE\r\n  JSON_EXTRACT(statusss, \"$.silencedBy[0]\") is null \r\n  and JSON_EXTRACT(statusss, \"$.state\") = \"active\"\r\n  and env='$ENV'  \r\n  and category = \"ZKLeader异常\"\r\nORDER BY startsAt"
    },
    {
     "rawSql": "SELECT\r\n  count(fingerprint) as \"ZK慢\"\r\nFROM alertmanager\r\nWHERE\r\n  JSON_EXTRACT(statusss, \"$.silencedBy[0]\") is null \r\n  and JSON_EXTRACT(statusss, \"$.state\") = \"active\"\r\n  and env='$ENV'  \r\n  and category = \"ZK慢\"\r\n  ORDER BY startsAt"
    }
   ]
  },
  {
   "title": "OBS告警",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  count(fingerprint) as \"成功率\"\r\nFROM alertmanager\r\nWHERE\r\n  JSON_EXTRACT(statusss, \"$.silencedBy[0]\") is null \r\n  and JSON_EXTRACT(statusss, \"$.state\") = \"active\"\r\n  and env='$ENV'  \r\n  and category = \"OBS成功率\"\r\nORDER BY startsAt "
    },
    {
     "rawSql": "SELECT\r\n  count(fingerprint) as \"延迟高\"\r\nFROM alertmanager\r\nWHERE\r\n  JSON_EXTRACT(statusss, \"$.silencedBy[0]\") is null \r\n  and JSON_EXTRACT(statusss, \"$.state\") = \"active\"\r\n  and env='$ENV'  \r\n  and category = \"OBS延迟高\"\r\nORDER BY startsAt"
    }
   ]
  },
  {
   "title": "ES告警",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(fingerprint) as \"ES\"\nFROM alertmanager\nWHERE\n  JSON_EXTRACT(statusss, \"$.silencedBy[0]\") is null \n  and JSON_EXTRACT(statusss, \"$.state\") = \"active\"\n  and env='$ENV'  \n  and category = \"ES\"\nORDER BY startsAt"
    }
   ]
  },
  {
   "title": "K8S告警",
   "type": "stat",
   "gridPos": { "h": 4, "w": 1, "x": 23, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  count(fingerprint) as \"K8S相关告警\"\r\nFROM alertmanager\r\nWHERE\r\n  JSON_EXTRACT(statusss, \"$.silencedBy[0]\") is null \r\n  and JSON_EXTRACT(statusss, \"$.state\") = \"active\"\r\n  and env='$ENV'  \r\n  and category = \"K8S\"\r\n  ORDER BY startsAt"
    }
   ]
  },
  {
   "title": "ELB告警",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 19, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  count(fingerprint) as \"成功率\"\r\nFROM alertmanager\r\nWHERE\r\n  JSON_EXTRACT(statusss, \"$.silencedBy[0]\") is null \r\n  and JSON_EXTRACT(statusss, \"$.state\") = \"active\"\r\n  and env='$ENV'  \r\n  and category = \"ELB\"\r\nORDER BY startsAt"
    }
   ]
  },
  {
   "title": "Kafka告警",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 21, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(fingerprint)\nFROM alertmanager\nWHERE\n  JSON_EXTRACT(statusss, \"$.silencedBy[0]\") is null \n  and JSON_EXTRACT(statusss, \"$.state\") = \"active\"\n  and env='$ENV'  \n  and category = \"KAFKA\"\nORDER BY startsAt"
    }
   ]
  },
  {
   "title": "其他",
   "type": "stat",
   "gridPos": { "h": 4, "w": 1, "x": 23, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  count(fingerprint) as \"K8S相关告警\"\r\nFROM alertmanager\r\nWHERE\r\n  JSON_EXTRACT(statusss, \"$.silencedBy[0]\") is null \r\n  and JSON_EXTRACT(statusss, \"$.state\") = \"active\"\r\n  and env='$ENV'  \r\n  and category = \"其他\"\r\nORDER BY startsAt"
    }
   ]
  },
  {
   "title": "告警详情列表",
   "type": "briangann-datatable-panel",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  startsAt AS \"告警开始时间\",\n  JSON_EXTRACT(labels, \"$.severity\") as '告警级别',\n  JSON_EXTRACT(labels, \"$.alertname\") as '告警名称',\n  description as \"告警详情\",\n  valuess as \"告警值大小\",\n  JSON_EXTRACT(statusss, \"$.state\") as '告警状态',\n  endsAt as \"告警结束时间\"\nFROM alertmanager\nWHERE\n  $__timeFilter(startsAt)\n  and JSON_EXTRACT(statusss, \"$.silencedBy[0]\") is null \n  and env='$ENV'  \nORDER BY startsAt desc"
    }
   ]
  },
  {
   "title": "今日告警总数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(fingerprint)\nFROM alertmanager\nwhere\nstartsAt > str_to_date(DATE_FORMAT(NOW(),'%Y-%m-%d'),'%Y-%m-%d %H:%i:%s') \nand  JSON_EXTRACT(statusss, \"$.silencedBy[0]\") is null \n  and env='$ENV'  \n;\n"
    }
   ]
  },
  {
   "title": "今日Critical告警",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(fingerprint)\nFROM alertmanager\nwhere\n JSON_EXTRACT(lower(labels), lower(\"$.severity\"))='critical'\n and  JSON_EXTRACT(statusss, \"$.silencedBy[0]\") is null \nAND startsAt > str_to_date(DATE_FORMAT(NOW(),'%Y-%m-%d'),'%Y-%m-%d %H:%i:%s')  \n  and env='$ENV'  \n;\n"
    }
   ]
  },
  {
   "title": "今日Warning告警",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(fingerprint)\nFROM alertmanager\nwhere \n JSON_EXTRACT(lower(labels), lower(\"$.severity\"))='warning'\n and  JSON_EXTRACT(statusss, \"$.silencedBy[0]\") is null \n AND startsAt > str_to_date(DATE_FORMAT(NOW(),'%Y-%m-%d'),'%Y-%m-%d %H:%i:%s')   \n  and env='$ENV'  \n ;\n"
    }
   ]
  },
  {
   "title": "今日Info告警",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(fingerprint)\nFROM alertmanager\nwhere \n JSON_EXTRACT(lower(labels), lower(\"$.severity\"))='info'\n and  JSON_EXTRACT(statusss, \"$.silencedBy[0]\") is null \n AND startsAt > str_to_date(DATE_FORMAT(NOW(),'%Y-%m-%d'),'%Y-%m-%d %H:%i:%s')   \n  and env='$ENV'  \n ;\n"
    }
   ]
  },
  {
   "title": "告警走势图(小时)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(startsAt,'1h',0) as 'time',\n  count(fingerprint) as 'value'\nFROM alertmanager\nwhere $__timeFilter(startsAt)\nand  JSON_EXTRACT(statusss, \"$.silencedBy[0]\") is null \n  and env='$ENV'  \ngroup by time;\n"
    }
   ]
  },
  { "title": "历史告警", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "历史告警总数(FROM:2024-10-09)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(fingerprint)\nFROM alertmanager\nwhere  \n   env='$ENV'  \n  and  JSON_EXTRACT(statusss, \"$.silencedBy[0]\") is null \n;"
    }
   ]
  },
  {
   "title": "Critical告警总数(FROM:2024-10-09)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(fingerprint)\nFROM alertmanager\nwhere  \n JSON_EXTRACT(lower(labels), lower(\"$.severity\"))='critical' \n and  JSON_EXTRACT(statusss, \"$.silencedBy[0]\") is null \n    and env='$ENV'  \n\n;"
    }
   ]
  },
  {
   "title": "Warning告警总数(FROM:2024-10-09)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(fingerprint)\nFROM alertmanager\nwhere \n JSON_EXTRACT(lower(labels), lower(\"$.severity\"))='warning' \n  and  JSON_EXTRACT(statusss, \"$.silencedBy[0]\") is null \n  and env='$ENV'  \n;"
    }
   ]
  },
  {
   "title": "Info告警总数(FROM:2024-10-09)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(fingerprint)\nFROM alertmanager\nwhere \n JSON_EXTRACT(lower(labels), lower(\"$.severity\"))='info'\n  and  JSON_EXTRACT(statusss, \"$.silencedBy[0]\") is null \n  and env='$ENV'  \n;"
    }
   ]
  }
 ]
}